### ISSUE TITLE
getAlbumTracks 400 Error when called often

### ISSUE THREAD

**Issue by michaeldomanek** [adamint/spotify-web-api-kotlin#310] opened 2022-04-11 22:55 UTC
**Describe the bug**
when I call `api.albums.getAlbumTracks()` for a lot of albums (e.g. 40 or 80), I get `Received Status Code 400. Error cause: malformed request sent` for some requests

**To Reproduce**
```
val api = spotifyAppApi()
val tracks = albumIds.flatMap { albumId ->
    api.albums.getAlbumTracks(albumId).getAllItemsNotNull()
}
```
create albumIds list from this file: [albumIds.txt](https://github.com/adamint/spotify-web-api-kotlin/files/8468151/albumIds.txt)

**Desktop:**
 - OS: Windows
 - Kotlin/JVM
 - Project with Java 17
 - Kotlin 1.6

**Comment by adamint** [comment] 2022-04-11 22:58
Does this occur for the same ids every time?

**Comment by michaeldomanek** [comment] 2022-04-11 23:45
no every time other ids and sometimes it doesn't happen and sometimes e.g 5 request fail (avg. 2-6 requests fail)

**Comment by adamint** [comment] 2022-04-13 06:18
I have reproduced this bug.

**Comment by adamint** [comment] 2022-04-15 04:10
Apologies, that was a typo. I have not been able to reproduce this bug on kotlin 1.6.20, version 3.8.6 @michaeldomanek after several thousands of requests. My code:

```kotlin
suspend fun main() = runBlocking {
    val api = spotifyAppApi("", "").build()
    api.spotifyApiOptions.enableDebugMode = true
    api.spotifyApiOptions.useCache = false

    val albumIds = File("${System.getProperty("user.home")}/Downloads/albumIds.txt").readText()
        .replace("[\\[\\]]".toRegex(), "")
        .split(", ")

    while (true) {
        val tracks = albumIds.map { albumId ->
            async {
                api.albums.getAlbumTracks(albumId).getAllItemsNotNull()
            }
        }.awaitAll()

        println(tracks)
    }

}
```

Can you give me more information around this behavior? Is there a particular exception or stacktrace you can share

**Comment by michaeldomanek** [comment] 2022-04-16 13:15
Hello @adamint thanks for looking into it.
I noticed this is a Java 17 Problem. I created a fresh Gradle Kotlin project and copied your code into it. 
When I select e.g. Oracle OpenJDK 17 or Eclipse Temurin AdoptOpenJDK 17 as Project SDK I get this error: [Stacktrace.txt](https://github.com/adamint/spotify-web-api-kotlin/files/8499957/Stacktrace.txt)
When I use e.g. OpenJDK 15 everything works.

**Comment by michaeldomanek** [comment] 2022-04-16 22:48
I created a new sample project to test it: [kotlin-gradle-example](https://github.com/michaeldomanek/kotlin-gradle-example)
The Stacktrace is from here if you want to look at it.

**Comment by adamint** [comment] 2022-04-19 05:25
Hi @michaeldomanek, I'm *still* unable to reproduce this with the given sample, on various JDKs (8, 11, 17). 
You reproduced it in this sample project? Do you have the debug console logs listing the request (from enableDebugMode)

**Comment by adamint** [comment] 2022-09-19 06:05
No additional info was provided, closing

**Closed by adamint** 2022-09-19 06:05 UTC
